Extend String Class
andela-obanwo/String-Class pull request #2
Opened 2017-01-03 16:58 UTC by andela-obanwo

2017-01-04 19:29 UTC, michaelogala requested changes

2017-01-04 19:29 UTC, andela-mogala commented on src/index.js
> +    const characters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
NITPICK: This code is duplicated in line 19. You can create an object property to hold this value.

2017-01-04 19:29 UTC, andela-mogala commented on src/index.js
> +    return this.replace(/[0-9]/g, (m) => {
NITPICK: Try to use an anonymous function here.

2017-01-06 09:49 UTC, azemoh commented on src/index.js
> +    if (/\d?/.test(this) && this.length === 1) {
**Nitpick - Code quality**

This logic can be expressed in a single RegEx. Also, the condition is a boolean expression which resolves to `True` or `False`. You can just return that, no need for the extra logic.
```javascript
return (/\d?/.test(this) && this.length === 1)
```

2017-01-06 09:49 UTC, azemoh commented on src/index.js
> +    if (/[a-zA-Z]/.test(this)) {
**Nitpick - Code Quality**
You can use the "Ignore case" (`//i`) flag to match both upper and lower case characters. This would be
`/[a-z]/i`

2017-01-06 09:49 UTC, azemoh commented on src/index.js
> +      ''.characters()[''.characters().indexOf(m) + 26]
**Code quality - Critical**
It is not optimal that you have to create a string instance to be able to assess the `characters` string. You are better off declaring it as a constant.

2017-01-06 09:49 UTC, azemoh commented on src/index.js
> +    if (/[^a-zA-Z]/.test(this)) {
See comment about Ignore case.

2017-01-06 09:49 UTC, azemoh commented on src/index.js
> +    return this.replace(/[0-9]/g, (m) => {
**Nitpick**
You don't need a counter variable here, the `replace` method passes yields a count argument to its callback function.
```javascript
return this.replace(/[0-9]/g, (m, count) => {
  ...
}
```

2017-01-06 09:49 UTC, azemoh commented on tests/tests.js
> +    };
**Testing**
You need more test cases to handle unusual punctuations, unusual spacing and special characters.

2017-01-06 09:49 UTC, azemoh commented on tests/tests.js
> +      .toEqual('Invalid String');
Good job checking for invalid inputs.

2017-01-17 10:42 UTC, merged